version: "3.9"
services:
  chrome:
    image: imlhx/chrome:latest
    container_name: chrome
    hostname: chrome
    privileged: true
    restart: always
    ports:
      - "3389:3389"
      - "5900:5900"
      - "5901:5901"
    environment:
      LANG: "C.utf8"
      RDP_USER: "rdp"
      RDP_PASS: "rdp"
      VNC_USER: "vnc"
      VNC_PASS: "12345678"
    volumes:
      - /etc/localtime:/etc/localtime
    healthcheck:
      test: [ "CMD-SHELL", "lsof -i :3389 -i :5900 -i :5901 >/dev/null 2>&1 || reboot" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s